name: CI
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./
      - name: Test run for latex
        run: latex small2e
      - name: Test run from pdflatex
        run: pdflatex sample2e
